name: 'Slack Notify Action'
description: 'Slack Notification for Github Actions'
author: baijunyao
inputs:
  slack_bot_token:
    description: 'Slack Bot Token'
    required: true
    default: ''
  slack_channel_id:
    description: 'Slack Channel'
    required: true
    default: ''
  github_context:
    description: 'GitHub Context'
    required: true
    default: ''
  github_token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}

runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bell'  
  color: 'red'
